### PR TITLE
Parcels

### PR DESCRIPTION
**Pull request by miriamseely**
Current draft of the Utah Parcels metadata. I previously had committed changes to the land ownership branch for parcels, but going forward, the parcels layer will live on this branch instead.

### CODE REVIEW

**Review by rkelson — COMMENTED** [review]
Hi Mariam - I am new to this metadata initiative so bare with me while I figure out the best way to review what looks like great work.

In my world the Basic parcels and the LIR parcels are 2 different things and it might be better to separate them instead of mashing them together. Unfortunately our new website kind of depicts them as similar where our old website had them better documented as two separate things.

We could keep both in one metadata but being a peculiar and particular kind of person, I like things to be as accurate a possible for our users. For instance the LIR attributes come from the State Auditor, they are only updated once a year, have very different attributes than the basic, and we do not have LIR parcels for every county. Maybe the Brief Summary, Summary, and What is the dataset, just need separate paragraphs with one pertaining to Basic and the other LIR.

Maybe take another stab at it and then I will add some final suggestions.

**Comment by steveoh** [comment]
We should absolutely split the metadata for these two products. They are distinctly different.

**Comment by miriamseely** [comment]
@rkelson Hello! Welcome to the metadata project, thank you for your feedback! I completely agree that they should be two separate sets of metadata. For now, let's have this .md file represent the Basic Parcels layer, and I will make another file for the LIR ones. @steveoh If I'm not mistaken, the LIR Parcels metadata will need its own ID and such, what's the process to get that ball rolling?

**Comment by steveoh** [comment]
> the LIR Parcels metadata will need its own ID and such, what's the process to get that ball rolling?

Skip those items for now.

**Comment by steveoh** [comment]
Did you intend to close this?

**Comment by miriamseely** [comment]
> Did you intend to close this?

I did, yes, since we are skipping Parcels for right now. Shall I reopen it? Are we planning on tackling splitting the LIR and Basic Parcels soon?

**Comment by steveoh** [comment]
I meant to skip only the lir and focus on the basic parcels.

**Comment by miriamseely** [comment]
Ah, I see. I started working on the Basic Parcels again today, should have that up for review sometime next week!

**Pull request closed without merging**
